# Generated by Django 4.1.7 on 2023-03-04 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("e_shop", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="uservoucher",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="uservoucher",
            name="voucher",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="e_shop.voucher"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="e_shop.item"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="e_shop.order"),
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(through="e_shop.OrderItem", to="e_shop.item"),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="order",
            name="user_voucher",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="e_shop.uservoucher",
            ),
        ),
    ]
