# Generated by Django 4.1.7 on 2023-03-04 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("e_shop", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uservoucher",
            options={"ordering": ["-id"]},
        ),
    ]
