version: "3"

volumes:
  postgres_data:

services:
  web:
    restart: always
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: e_shop_web
    command: > 
      bash -c "python manage.py makemigrations && 
      python manage.py migrate && 
      python manage.py collectstatic --noinput && 
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../project:/src
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    env_file:
      - ../project/.env
    ports:
      - "5444:5432"
